import { formatIsoDate } from "../payApps/g703Math";
import type { ChangeOrderInput, G702Figures, OwnerPayAppInput, SheetLine, SheetTotals, SubPayAppInput, SubcontractInput } from "./inputTypes";
import { PdfWriter, type TableColumn } from "./pdfWriter";
import { bpsPercent, pdfAmount, pdfSignedAmount } from "./pdfText";

/**
 * PDF builders for billing documents. Titles say "-style": these are TradePulse Pay documents that
 * follow the familiar AIA layout, never reproductions of AIA forms. Amounts are US dollars.
 */

const FOOTER = "Generated by TradePulse Pay. Amounts in US dollars. Not an AIA document.";

function dateText(iso: string | null): string {
  return iso === null ? "Not set" : formatIsoDate(iso);
}

const G703_COLUMNS: TableColumn[] = [
  { title: "A Item", width: 34 },
  { title: "B Description of work", width: 170, wrap: true },
  { title: "C Scheduled value", width: 62, align: "right" },
  { title: "D From previous", width: 60, align: "right" },
  { title: "E This period", width: 58, align: "right" },
  { title: "F Materials stored", width: 58, align: "right" },
  { title: "G Completed & stored", width: 66, align: "right" },
  { title: "G/C %", width: 40, align: "right" },
  { title: "H Balance to finish", width: 64, align: "right" },
  { title: "I Retainage", width: 50, align: "right" },
];

function sheetRow(l: SheetLine): string[] {
  return [
    l.item,
    l.description,
    pdfAmount(l.scheduledValueCents),
    pdfAmount(l.previousCents),
    pdfAmount(l.thisPeriodCents),
    pdfAmount(l.storedCents),
    pdfAmount(l.totalCents),
    l.percentText,
    pdfAmount(l.balanceCents),
    pdfAmount(l.retainageCents),
  ];
}

function totalsRow(t: SheetTotals): string[] {
  return [
    "",
    "Grand totals",
    pdfAmount(t.scheduledValueCents),
    pdfAmount(t.previousCents),
    pdfAmount(t.thisPeriodCents),
    pdfAmount(t.storedCents),
    pdfAmount(t.totalCents),
    t.percentText,
    pdfAmount(t.balanceCents),
    pdfAmount(t.retainageCents),
  ];
}

function g702Lines(w: PdfWriter, f: G702Figures, retainageBps: number): void {
  w.amountLines([
    { label: "1. Original contract sum", amount: pdfAmount(f.originalContractSumCents) },
    { label: "2. Net change by change orders", amount: pdfSignedAmount(f.netChangeOrdersCents) },
    { label: "3. Contract sum to date (line 1 + 2)", amount: pdfAmount(f.contractSumToDateCents) },
    { label: "4. Total completed & stored to date (column G)", amount: pdfAmount(f.completedAndStoredCents) },
    { label: `5. Retainage (${bpsPercent(retainageBps)}), column I`, amount: pdfAmount(f.retainageCents) },
    { label: "    a. on completed work", amount: pdfAmount(f.retainageWorkCents) },
    { label: "    b. on stored material", amount: pdfAmount(f.retainageStoredCents) },
    { label: "6. Total earned less retainage (line 4 - 5)", amount: pdfAmount(f.earnedLessRetainageCents) },
    { label: "7. Less previous certificates for payment", amount: pdfAmount(f.previousCertificatesCents) },
    { label: "8. Current payment due", amount: pdfAmount(f.currentPaymentDueCents), bold: true },
    { label: "9. Balance to finish, including retainage (line 3 - 6)", amount: pdfAmount(f.balanceToFinishInclRetainageCents) },
  ]);
}

function signatureBlock(w: PdfWriter, parties: readonly string[]): void {
  w.space(10);
  for (const p of parties) {
    w.text(`${p}: ______________________________   Date: ______________`, { size: 9 });
    w.space(8);
  }
}

/** Sub pay app: a G702-style summary page and G703-style continuation sheet(s). */
export async function buildSubPayAppPdf(d: SubPayAppInput, asOf: number): Promise<Uint8Array> {
  const appNo = d.applicationNo !== null ? `Application No. ${d.applicationNo}` : d.periodLabel;
  const w = await PdfWriter.create({
    title: `${appNo} - ${d.subName} - ${d.projectTitle}`,
    subject: "Application and Certificate for Payment (AIA G702-style)",
    asOf,
    footer: FOOTER,
  });
  w.heading("Application and Certificate for Payment");
  w.text("AIA G702-style summary prepared in TradePulse Pay", { size: 9, muted: true });
  w.space(6);
  w.text(appNo, { size: 12, bold: true });
  w.space(4);
  w.fields([
    ["To (contractor)", d.gcName],
    ["From (subcontractor)", d.subName],
    ["Project", d.projectTitle],
    ["Project address", d.projectAddress],
    ...(d.ownerName ? ([["Owner", d.ownerName]] as [string, string][]) : []),
    ["Subcontract", d.agreementNumber],
    ["Period", `${dateText(d.periodStart)} to ${dateText(d.periodEnd)}`],
    ["Period end", dateText(d.periodEnd)],
    ["Due date", dateText(d.dueDate)],
    ["Status", d.statusLabel],
    ["Figures", d.basisLabel],
  ]);
  w.rule();
  g702Lines(w, d.figures, d.retainageBps);
  w.rule();
  w.text("Change order summary", { size: 10, bold: true });
  if (d.changeOrders.length === 0) w.text("No approved change orders.", { size: 9 });
  else
    w.fields(
      d.changeOrders.map((co) => [co.label, `${co.title}  ${pdfSignedAmount(co.amountCents)}${co.approvedOn ? `  (approved ${co.approvedOn})` : ""}`] as const),
      { size: 9, labelWidth: 60 },
    );
  if (d.approvedBy) {
    w.space(4);
    w.text(`Approved by ${d.approvedBy}${d.approvedOn ? ` on ${d.approvedOn}` : ""}.`, { size: 9 });
  }
  w.space(4);
  w.text(
    "The subcontractor certifies that, to the best of its knowledge, the work covered by this application has been completed in accordance with the subcontract, and that amounts previously paid have been applied to the work.",
    { size: 8.5, muted: true },
  );
  signatureBlock(w, ["Subcontractor", "Contractor (certified for payment)"]);

  w.addPage("landscape");
  w.heading("Continuation Sheet", 13);
  w.text(`AIA G703-style continuation sheet  |  ${appNo}  |  ${d.subName}  |  ${d.projectTitle}`, { size: 8.5 });
  w.text(`Period end ${dateText(d.periodEnd)}  |  Retainage ${bpsPercent(d.retainageBps)} per line, rounded per line`, { size: 8.5, muted: true });
  w.space(6);
  w.table(G703_COLUMNS, [...d.lines.map((l) => ({ cells: sheetRow(l) })), { cells: totalsRow(d.totals), bold: true }]);
  return await w.save();
}

/** Owner pay app: the GC's G702/G703-style application to the owner, prime lines only. */
export async function buildOwnerPayAppPdf(d: OwnerPayAppInput, asOf: number): Promise<Uint8Array> {
  const appNo = `Application No. ${d.applicationNo}`;
  const w = await PdfWriter.create({
    title: `${appNo} - ${d.ownerName} - ${d.projectTitle}`,
    subject: "Application for Payment to Owner (AIA G702-style)",
    asOf,
    footer: FOOTER,
  });
  w.heading("Application for Payment to Owner");
  w.text("AIA G702-style summary prepared in TradePulse Pay", { size: 9, muted: true });
  w.space(6);
  w.text(appNo, { size: 12, bold: true });
  w.space(4);
  w.fields([
    ["To (owner)", d.ownerName],
    ["From (contractor)", d.gcName],
    ["Project", d.projectTitle],
    ["Project address", d.projectAddress],
    ["Period", `${dateText(d.periodStart)} to ${dateText(d.periodEnd)}`],
    ["Period end", dateText(d.periodEnd)],
    ["Status", d.statusLabel],
    ["Submitted", d.submittedOn ?? "Not submitted"],
    ...(d.approvedBy ? ([["Approved by", `${d.approvedBy}${d.approvedOn ? ` on ${d.approvedOn}` : ""}`]] as [string, string][]) : []),
  ]);
  w.rule();
  g702Lines(w, d.figures, d.retainageBps);
  w.text("Retainage is computed and rounded on each prime line.", { size: 8.5, muted: true });
  signatureBlock(w, ["Contractor", "Owner"]);

  w.addPage("landscape");
  w.heading("Continuation Sheet", 13);
  w.text(`AIA G703-style continuation sheet  |  ${appNo}  |  ${d.projectTitle}  |  Period end ${dateText(d.periodEnd)}`, { size: 8.5 });
  w.space(6);
  w.table(G703_COLUMNS, [...d.lines.map((l) => ({ cells: sheetRow(l) })), { cells: totalsRow(d.totals), bold: true }]);
  return await w.save();
}

/** One change order with the contract sum before and after it. */
export async function buildChangeOrderPdf(d: ChangeOrderInput, asOf: number): Promise<Uint8Array> {
  const heading = d.scope === "prime" ? `Prime Change Order No. ${d.number} (${d.label})` : `Change Order No. ${d.number} (${d.label})`;
  const w = await PdfWriter.create({
    title: `${heading} - ${d.title}`,
    subject: "Change Order (AIA G701-style)",
    asOf,
    footer: FOOTER,
  });
  w.heading(heading);
  w.text(d.scope === "prime" ? "AIA G701-style change to the prime contract" : "AIA G701-style change to the subcontract", {
    size: 9,
    muted: true,
  });
  w.space(6);
  w.fields([
    ["Project", d.projectTitle],
    ["Project address", d.projectAddress],
    [d.partyFrom.role, d.partyFrom.name],
    [d.partyTo.role, d.partyTo.name],
    ["Contract", d.contractRef],
    ["Title", d.title],
    ["Status", d.statusLabel],
    ["Requested", d.requestedOn ?? "Not submitted"],
  ]);
  if (d.description.trim()) {
    w.space(4);
    w.text("Description", { size: 10, bold: true });
    w.text(d.description, { size: 9.5 });
  }
  w.rule();
  w.amountLines([
    { label: "Original contract sum", amount: pdfAmount(d.originalContractSumCents) },
    { label: "Net change by previously approved change orders", amount: pdfSignedAmount(d.previousContractSumCents - d.originalContractSumCents) },
    { label: "Previous contract sum", amount: pdfAmount(d.previousContractSumCents) },
    { label: `This change order ${d.amountCents < 0 ? "(deduction)" : "(addition)"}`, amount: pdfSignedAmount(d.amountCents), bold: true },
    { label: d.approved ? "New contract sum to date" : "Contract sum to date if approved", amount: pdfAmount(d.newContractSumCents), bold: true },
  ]);
  w.fields([
    ["Contract time change", d.scheduleDays === null ? "None" : `${d.scheduleDays > 0 ? "+" : ""}${d.scheduleDays} ${Math.abs(d.scheduleDays) === 1 ? "day" : "days"}`],
  ]);
  w.rule();
  if (d.approved) w.text(`Approved by ${d.approvedBy ?? "the deciding party"}${d.approvedOn ? ` on ${d.approvedOn}` : ""}.`, { size: 10 });
  else w.text("Not approved. This change order does not change the contract sum until it is approved.", { size: 10 });
  signatureBlock(w, [d.partyFrom.role, d.partyTo.role]);
  return await w.save();
}

/** The executed subcontract: key terms, then the agreement text exactly as stored. */
export async function buildSubcontractPdf(d: SubcontractInput, asOf: number): Promise<Uint8Array> {
  const w = await PdfWriter.create({
    title: `Subcontract ${d.agreementNumber} - ${d.subName}`,
    subject: "Subcontract Agreement (AIA-style, A401-style)",
    asOf,
    footer: `${FOOTER}  Subcontract ${d.agreementNumber}`,
  });
  w.heading("Subcontract Agreement");
  w.text("AIA-style subcontract (A401-style) between contractor and subcontractor, prepared in TradePulse Pay", { size: 9, muted: true });
  w.space(6);
  w.fields([
    ["Agreement", d.agreementNumber],
    ["Contractor", d.gcName],
    ["Subcontractor", d.subName],
    ["Project", d.projectTitle],
    ["Project address", d.projectAddress],
    ["Trade", d.trade],
    ["Contract sum", pdfAmount(d.contractSumCents)],
    ["Retainage", d.retainageText],
    ["Payment terms", d.paymentTermsText],
    ["Governing law", d.governingLaw ?? "Not stated"],
    ["Status", d.statusLabel],
    ["Executed", d.executedOn ?? "Not executed"],
  ]);
  w.rule();
  w.text(d.contractText, { size: 9 });
  return await w.save();
}
